### ISSUE TITLE
Refactor quartz methods job to build and trigger 

### ISSUE THREAD

**Issue by Jossec101** [Elenpay/NodeGuard#10]
I see this pattern repeated a lot, maybe it could be refactored in just a method, but its ok for now

_Originally posted by @Jossec101 in https://github.com/Elenpay/NodeGuard/pull/5#discussion_r1058295901_

**Comment by RodriFS** [comment]
Created PR for this issue: https://github.com/Elenpay/NodeGuard/pull/13

**Comment by Jossec101** [comment]
Close as of #13
