### ISSUE TITLE
Weird redirection and sent to the main page

### ISSUE THREAD

**Issue by markettes** [Elenpay/NodeGuard#33]
Weird redirection to /setup-internal-wallet. Showed in video.

https://user-images.githubusercontent.com/33052423/210838663-f4fcaa6d-06ad-41f7-9ee1-b56baf7b714a.mov

**Comment by Jossec101** [comment]
Indeed, probably related with https://github.com/Elenpay/NodeGuard/blob/6d5c64e62b521b85dd68822410698646a0053d08/src/Shared/MainLayout.razor#L75-L90

**Comment by Jossec101** [comment]
Weird, its not happening to me on #37 dev branch on local.

**Comment by Jossec101** [comment]
Its is related to the internal wallet mnemonic not being set probably, on production it does not happen
